# Generated by Django 5.1.7 on 2026-06-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
        ('stores', '0002_alter_store_options_alter_storeproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='backup_phone',
            field=models.CharField(blank=True, help_text='Alternative contact number if primary is unreachable', max_length=20, verbose_name='Backup phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_apartment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apartment / Office'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_floor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup from store'), ('delivery', 'Home delivery')], default='pickup', max_length=20, verbose_name='Delivery type'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='stores.store', verbose_name='Pickup store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
    ]
