# Generated by Django 5.1.7 on 2026-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_expansion_manager',
            field=models.BooleanField(default=False, help_text='Может создавать/редактировать магазины и назначать сотрудников', verbose_name='Управляющий филиалами'),
        ),
    ]
