# Generated by Django 5.1.7 on 2026-06-10 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_expansion_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_hr_manager',
            field=models.BooleanField(default=False, help_text='Can manage employee profiles, documents, and payroll details', verbose_name='HR manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Set to True after user clicks the confirmation link', verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_expansion_manager',
            field=models.BooleanField(default=False, help_text='Can create/edit stores and assign store staff', verbose_name='Expansion manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +44 77 1234 5678', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 key for Google Authenticator. Empty = 2FA disabled.', max_length=64, verbose_name='TOTP secret'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(blank=True, help_text='Passport number or national ID card number', max_length=50, verbose_name='Passport number')),
                ('right_to_work', models.FileField(blank=True, help_text='Visa, BRP, share code screenshot, or work authorisation', null=True, upload_to='hr/right_to_work/', verbose_name='Right to work document')),
                ('ni_number', models.CharField(blank=True, help_text='National Insurance (UK) or Social Security Number (US)', max_length=20, verbose_name='NI / SSN')),
                ('proof_of_address', models.FileField(blank=True, help_text='Utility bill or bank statement (last 3 months)', null=True, upload_to='hr/address/', verbose_name='Proof of address')),
                ('emergency_name', models.CharField(blank=True, max_length=100, verbose_name='Emergency contact name')),
                ('emergency_phone', models.CharField(blank=True, max_length=30, verbose_name='Emergency contact phone')),
                ('emergency_relationship', models.CharField(blank=True, help_text='e.g. spouse, parent, sibling', max_length=50, verbose_name='Relationship')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank name')),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number', max_length=30, verbose_name='Account number')),
                ('bank_sort_code', models.CharField(blank=True, help_text='Sort code (UK) or routing number (US)', max_length=20, verbose_name='Sort code / Routing')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job title')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee profile',
                'verbose_name_plural': 'Employee profiles',
            },
        ),
    ]
