# Generated by Django 5.1.7 on 2026-06-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['city', 'name'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'verbose_name': 'Store stock', 'verbose_name_plural': 'Stock by stores'},
        ),
        migrations.AlterModelOptions(
            name='storestaff',
            options={'verbose_name': 'Store employee', 'verbose_name_plural': 'Store employees'},
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='store',
            name='work_hours',
            field=models.CharField(blank=True, default='09:00–21:00', max_length=200, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='storestaff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='storestaff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('senior', 'Senior seller'), ('seller', 'Seller')], default='seller', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='storestaff',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='storestaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_workships', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
    ]
