# Generated by Django 5.1.7 on 2026-06-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='e.g. EUR, GBP', max_length=3, unique=True, verbose_name='Currency code')),
                ('rate', models.DecimalField(decimal_places=6, help_text='How many units of this currency per 1 USD', max_digits=10, verbose_name='Rate to USD')),
                ('symbol', models.CharField(help_text='e.g. €, £', max_length=5, verbose_name='Symbol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange rate',
                'verbose_name_plural': 'Exchange rates',
            },
        ),
    ]
