# Generated by Django 5.1.7 on 2026-06-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='e.g. Screen size, RAM, Joysticks', max_length=100, verbose_name='Field name')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes / No')], default='text', max_length=20, verbose_name='Field type')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_fields', to='catalog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category spec field',
                'verbose_name_plural': 'Category spec fields',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
