# Generated by Django 5.1.7 on 2026-06-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_spec_fields_and_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryspecfield',
            name='is_active',
        ),
    ]
