# Generated by Django 5.1.7 on 2026-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_alter_review_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, help_text='What could be improved?', verbose_name='What I did not like'),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, help_text='What did you like about the product?', verbose_name='What I liked'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, verbose_name='Overall review'),
        ),
    ]
